[build]
  command = "pnpm exec tsc -p netlify/tsconfig.json --noEmit"
  publish = "netlify/public"
  functions = "netlify/functions"

[build.environment]
  NPM_CONFIG_PRODUCTION = "false"

[functions]
  node_bundler = "esbuild"
